### PR TITLE
Use newer image for maven on windows (currently 3.8.1)

### PR DESCRIPTION
**Pull request by timja**
https://github.com/jenkinsci/plugin-pom/pull/419#issuecomment-882796440

cc @jglick @dduportal 

previous image hasn't been updated in a year, looks like vendor specific images were added

### CODE REVIEW

**Review by jglick — APPROVED** [review]
:man_shrugging: if it works

**Comment by jglick** [comment]
Noticed in https://github.com/jenkinsci/build-token-root-plugin/pull/63 BTW.

**Comment by jglick** [comment]
Let me know when this deploys.

**Comment by timja** [comment]
Not 100% sure this is the repo it may also be https://github.com/jenkins-infra/docker-inbound-agents/blob/main/maven/Dockerfile.windows

but given we use jenkins4eval i think it's this one

**Comment by jglick** [comment]
Not live yet.

**Comment by timja** [comment]
The build failed, I've re-triggered to see if it was a one-off

**Comment by timja** [comment]
Looks like I triggered the wrong build, triggered the right one now:
https://trusted.ci.jenkins.io:1443/job/Containers/job/jnlp-agents/865/

**Comment by jglick** [comment]
Still not deployed.

**Comment by timja** [comment]
For some reason we were using jenkins4eval which was last updated 1 year ago manually by @slide 

I've now switched us to https://hub.docker.com/layers/109369808/jenkins/jnlp-agent-maven/windows-nanoserver/images/sha256-e66bc1a2f1045a2f85b6459f2c63349c823048a66c5e1c72bab39235744e3d3b?context=repo

Which was updated yesterday.

Let's see if it works

**Comment by timja** [comment]
https://github.com/jenkinsci/jnlp-agents/pull/28

**Pull request merged**
