### PR TITLE
Initial Windows support for maven docker image

### PR DESCRIPTION
**Pull request by slide**
This depends on several other docker images being pushed to docker hub. Just wanted to get it in here to get some feedback started.

### CODE REVIEW

**Comment by rtyler** [comment]
@slide does this require a Windows environment? Or can this be plugged into the `Makefile` tooling already present in this environment?

**Comment by slide** [comment]
To build windows containers, you need a windows system. We're in kind of a chicken and egg problem as there are no Windows agents that have docker installed to build stuff like this yet, but we need these type of images to start some of that...

**Comment by slide** [comment]
@jglick, correct, you have to have a Windows system to build a Windows docker image. I think we can add docker to the Windows VM templates, but I will have to look into it.

AppVeyor does support Docker builds, however, it is using Windows Server 2016 instead of Windows Server 2019 (which has better container support).

**Comment by jglick** [comment]
Well in the short term I guess we would just manually publish images built from this work. There are not that many changes anyway.

**Comment by slide** [comment]
Agreed, we just need someone with Windows platform(s) (2016 and 2019 would be the best if possible) who can build the images and then publish them.

**Comment by slide** [comment]
I think I can fairly easily enable Windows docker nodes on ci.jenkins.io and trusted.ci. I am requesting access to ci.jenkins.io in order to enable it.

**Comment by slide** [comment]
I have successfully setup a Windows docker agent on ci.jenkins.io, so we should be able to build these images somewhat soon. I will determine how it will work best to fit into the current Makefile like framework (won't be in Makefile, but I'll try and maintain a similar idea).

**Comment by slide** [comment]
We have the capability to build these on both ci.j.io and trusted now. I need to upgrade the containers to use the "official" maven images now.

**Comment by slide** [comment]
@rtyler This is ready for review if you have some time.

**Comment by slide** [comment]
Close and resubmit because I messed something up

**Comment by jglick** [comment]
⇒ #12

**Pull request closed without merging**
