### PR TITLE
Add Python agents

### PR DESCRIPTION
**Pull request by hodossy**
Agent images to run Python based pipelines

### CODE REVIEW

**Comment by hodossy** [comment]
Thanks for merging! When can I expect the new image to be published?

**Comment by olblak** [comment]
@hodossy  I just notice that a build is failing because this image can't be published :) a link here to a jira issue would have been nice to understand the context anyway Apparently nobody created the appropriate docker repository which I am going to do now :)

**Comment by olblak** [comment]
[INFRA-2277](https://issues.jenkins-ci.org/browse/INFRA-2277)

**Comment by olblak** [comment]
[INFRA-2277|https://issues.jenkins-ci.org/browse/INFRA-2277] is now done-done and the images are available on [DockerHub|https://cloud.docker.com/u/jenkins/repository/docker/jenkins/jnlp-agent-python/general] thanks @hodossy for this contribution, and meanwhile I created [JENKINS-59474|https://issues.jenkins-ci.org/browse/JENKINS-59474] in order to have images with jnlp using jdk11

**Pull request merged**
